# Generated by Django 5.2.8 on 2025-11-06 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('bank_account', 'Bank Account'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash')], max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Payout Account',
                'verbose_name_plural': 'Payout Accounts',
                'db_table': 'payout_accounts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('manual', 'Manual'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('next_payout_date', models.DateField(blank=True, null=True)),
                ('minimum_payout_amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=12)),
                ('auto_process', models.BooleanField(default=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_schedule', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Payout Schedule',
                'verbose_name_plural': 'Payout Schedules',
                'db_table': 'payout_schedules',
            },
        ),
        migrations.CreateModel(
            name='VendorBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('on_hold_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('hold_reason', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Balance',
                'verbose_name_plural': 'Vendor Balances',
                'db_table': 'vendor_balances',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payout_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('manual', 'Manual')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('commission_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('processor_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendors.vendor')),
                ('payout_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payouts.payoutaccount')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'db_table': 'payouts',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='payouts_vendor__f8d117_idx'), models.Index(fields=['reference_number'], name='payouts_referen_67f7a3_idx'), models.Index(fields=['requested_at'], name='payouts_request_9ecb76_idx')],
            },
        ),
    ]
