# Generated by Django 5.2.8 on 2025-11-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('form', 'Form'), ('document_upload', 'Document Upload'), ('verification', 'Verification'), ('agreement', 'Agreement')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('form_config', models.JSONField(blank=True, default=dict)),
                ('document_types', models.JSONField(blank=True, default=list)),
                ('agreement_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding Step',
                'verbose_name_plural': 'Onboarding Steps',
                'db_table': 'onboarding_steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VendorOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_steps', models.ManyToManyField(blank=True, related_name='completed_onboardings', to='onboarding.onboardingstep')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.onboardingstep')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Onboarding',
                'verbose_name_plural': 'Vendor Onboardings',
                'db_table': 'vendor_onboardings',
            },
        ),
        migrations.CreateModel(
            name='OnboardingStepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_data', models.JSONField(blank=True, default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingstep')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='onboarding.vendoronboarding')),
            ],
            options={
                'verbose_name': 'Onboarding Step Completion',
                'verbose_name_plural': 'Onboarding Step Completions',
                'db_table': 'onboarding_step_completions',
                'unique_together': {('onboarding', 'step')},
            },
        ),
    ]
