# Generated by Django 5.2.8 on 2025-11-06 11:36

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_slug', models.SlugField(max_length=300, unique=True)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company'), ('corporation', 'Corporation')], max_length=50)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('website', models.URLField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='US', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business_registration_document', models.FileField(blank=True, null=True, upload_to='vendor/documents/registration/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.BigIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='vendors_user_id_5e6fe3_idx'), models.Index(fields=['status'], name='vendors_status_079e23_idx'), models.Index(fields=['business_slug'], name='vendors_busines_65d430_idx'), models.Index(fields=['created_at'], name='vendors_created_cf453f_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('monthly_views', models.JSONField(default=dict)),
                ('monthly_sales', models.JSONField(default=dict)),
                ('monthly_orders', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Analytics',
                'verbose_name_plural': 'Vendor Analytics',
                'db_table': 'vendor_analytics',
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_proof', 'Identity Proof'), ('address_proof', 'Address Proof'), ('business_license', 'Business License'), ('tax_certificate', 'Tax Certificate'), ('bank_proof', 'Bank Account Proof'), ('other', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='vendor/documents/')),
                ('document_name', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.BigIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Document',
                'verbose_name_plural': 'Vendor Documents',
                'db_table': 'vendor_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('auto_accept_orders', models.BooleanField(default=True)),
                ('low_stock_alert', models.BooleanField(default=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('show_social_media', models.BooleanField(default=True)),
                ('show_contact_info', models.BooleanField(default=True)),
                ('show_sales_count', models.BooleanField(default=True)),
                ('custom_commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Settings',
                'verbose_name_plural': 'Vendor Settings',
                'db_table': 'vendor_settings',
            },
        ),
        migrations.CreateModel(
            name='VendorSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Social Media',
                'verbose_name_plural': 'Vendor Social Media',
                'db_table': 'vendor_social_media',
                'unique_together': {('vendor', 'platform')},
            },
        ),
    ]
